### ISSUE TITLE
stage 3 syntax raise errors, and fail

### ISSUE THREAD

**Issue by swyxio** [ChristopherBiscardi/gatsby-theme#19]
try to copy code that uses public class fields.

```js
(node:11989) UnhandledPromiseRejectionWarning: SyntaxError: unknown: Support for the experimental syntax 'classProperties' isn't currently ena
bled (34:9):

  32 | 
  33 | class SignUp extends React.Component {
> 34 |   state = {
     |         ^
  35 |     submitted: false,
  36 |   }
  37 | 

Add @babel/plugin-proposal-class-properties (https://git.io/vb4SL) to the 'plugins' section of your Babel config to enable transformation.
    at Object.raise (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:6325:17)
    at Object.expectPlugin (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:7647:18)
    at Object.parseClassProperty (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:10830:12)
    at Object.pushClassProperty (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:10795:30)
    at Object.parseClassMemberWithIsStatic (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:10734:14)
    at Object.parseClassMember (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:10668:10)
    at withTopicForbiddingContext (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:10623:14)
    at Object.withTopicForbiddingContext (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:9702:14)
    at Object.parseClassBody (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:10600:10)
    at Object.parseClass (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:10574:22)
    at Object.parseStatementContent (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:9871:21)
    at Object.parseStatement (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:9829:17)
    at Object.parseBlockOrModuleBlockBody (/Users/swyx/Work/swyxdotio/node_modules/@babel/parser/lib/index.js:10405:25)
```

**Comment by swyxio** [comment]
reasonable to include `babel-preset-react`?
